modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Khorbos/KBlasting/issues"
[[mods]]
modId="kblasting"
version="${file.jarVersion}"
displayName="KBlasting"
description='''
Blast furnace, but better
'''

[[dependencies.kblasting]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kblasting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
